/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long n) {
        for (int i = 2; i <= Math.sqrt(n); i++) {if (n%i == 0) {return false;}}
        if (n <= 1) {return false;}
        return true;
    }
    public long firstPrimeNumberIn(String n) {
        for (int i = 0; i < n.length() - 10; i++) {
            Long a = Long.parseLong(n.substring(i,i+10));
        }
        return a;
    }
}
